//mods.nuclearcraft.manufactory.addRecipe([itemInput, itemOutput, {timeMultiplier (double), powerMultiplier (double), processRadiation (double)}]);


mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "prismarine"}), <minecraft:prismarine_crystals>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "steel"}), <mekanism:ingot:4>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "aquamarine"}), <astralsorcery:itemcraftingcomponent>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "soul_sand"}), <minecraft:soul_sand>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "cobalt"}), <tconstruct:nuggets>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "ender"}), <minecraft:ender_pearl>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "aluminum"}), <sky_orchards:amber_aluminum>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "manyullyn"}), <tconstruct:nuggets:2>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "glowstone"}), <minecraft:glowstone_dust>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "clay"}), <minecraft:clay_ball>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "ironbars"}), <minecraft:iron_bars>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "gold"}), <sky_orchards:amber_gold>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "lithium"}), <nuclearcraft:dust:6>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "platinum"}), <thermalfoundation:material:134>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "cobblestone"}), <minecraft:cobblestone>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "thorium"}), <nuclearcraft:dust:3>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "lapis_lazuli"}), <minecraft:dye:4>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "tin"}), <sky_orchards:amber_tin>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "tritanium"}), <matteroverdrive:tritanium_ingot>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "copper"}), <sky_orchards:amber_copper>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "invar"}), <thermalfoundation:material:162>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "netherrack"}), <minecraft:netherrack>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "ardite"}), <tconstruct:nuggets:1>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "sapphire"}), <practicallogistics2:sapphire>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "electrum"}), <thermalfoundation:material:161>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "nickel"}), <sky_orchards:amber_nickel>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "glass"}), <minecraft:glass>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "obsidian"}), <minecraft:obsidian>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "dirt"}), <minecraft:dirt>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "magnesium"}), <nuclearcraft:dust:7>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "osmium"}), <sky_orchards:amber_osmium>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "quartz"}), <minecraft:quartz>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "bone"}), <minecraft:bone>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "lead"}), <sky_orchards:amber_lead>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "bronze"}), <thermalfoundation:material:99>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "gravel"}), <minecraft:gravel>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "sand"}), <minecraft:sand>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "diamond"}), <minecraft:diamond>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "dilithium"}), <matteroverdrive:dilithium_crystal>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "seared_brick"}), <tconstruct:materials>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "coal"}), <minecraft:coal>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "iron"}), <sky_orchards:amber_iron>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "silver"}), <sky_orchards:amber_silver>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "uranium"}), <nuclearcraft:dust:4>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "boron"}), <nuclearcraft:dust:5>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "emerald"}), <minecraft:emerald>]);
mods.nuclearcraft.manufactory.addRecipe([<resourcehogs:bacon>.withTag({ResourceType: "redstone"}), <minecraft:redstone>]);

//Wool from Cotton Amber
mods.nuclearcraft.manufactory.addRecipe([<sky_orchards:amber_cottonwood>, <minecraft:wool>]);
mods.nuclearcraft.manufactory.addRecipe([<sky_orchards:acorn_cottonwood>, <minecraft:string>]);